from setuptools import setup, find_packages

setup(
    name='ComplexNetworkOperation',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[
        'platform',
        'sys',
        'os',
        'csv',
        'glob',
        'shutil',
        'warnings',
        're',
        'pathlib',
        'importlib',
        'pkgutil',
        # 'openpyxl',
        # 'dataclasses',
        'itertools',
        'enum',
        'time',
        'timeit',
        'datetime',
        'numpy',
        'pandas',
        'networkx',
        'matplotlib',
        'logging',
        'pickle',
        'typing',
        'functools',
        'random',
        'string',
        'locale',
        'subprocess',
        'base64',
        'multiprocessing',
        'noise',
        'ast',
        'builtins',
        'chardet',
        # 'numba',
        # 'cv2',
        # 'scipy',
        # 'igraph',
        # 'drawsvg',
        # 'fitz',
        # 'svglib',
        # 'reportlab',
    ],
    author='Complex System Explorer',
    author_email='',  #TODO 
    description='复杂系统实验室。提供探索、研究、展示、可视化各类复杂系统。',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/ComplexSystemLab/ComplexNetworkOperation.git',
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='==3.12',
    license='MIT',
)
